"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.version = void 0; // generated by genversion

var version = '0.0.1';
exports.version = version;
//# sourceMappingURL=version.js.map